# Generated by Django 5.1 on 2024-08-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('image', models.ImageField(null=True, upload_to='static/images/', verbose_name='Фото')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('phone', models.CharField(max_length=255, verbose_name='№ телефона')),
                ('e_mail', models.EmailField(max_length=255, verbose_name='Электронная почта')),
                ('nickname_tg', models.CharField(max_length=255, null=True, verbose_name='Никнейм Telegram')),
                ('nickname_inst', models.CharField(max_length=255, null=True, verbose_name='Никнейм Instagram')),
                ('group_number', models.CharField(max_length=255, verbose_name='№ группы')),
                ('number_of_points', models.IntegerField(default=0, max_length=100, verbose_name='Количество баллов')),
                ('status', models.CharField(max_length=100, verbose_name='Статус')),
                ('package', models.CharField(max_length=255, verbose_name='Пакет')),
                ('internship', models.CharField(max_length=255, verbose_name='Стажировка')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
